public enum Platform: Swift.String, Swift.Sendable, Swift.Hashable, Swift.CaseIterable {
    case macOS = "macos"
    case iOS = "ios"
    case tvOS = "tvos"
    case watchOS = "watchos"
    case visionOS = "visionos"
    case macCatalyst = "maccatalyst"
    case driverKit = "driverkit"
    case linux = "linux"
    case android = "android"
    case windows = "windows"
    case wasi = "wasi"
    case freeBSD = "freebsd"
    case openBSD = "openbsd"
}
